### ISSUE TITLE
Can't run the web client 

### ISSUE THREAD

**Issue by torrober** [junhoyeo/threads-api#21]
Hi, first of all, amazing job at creating an API at such a fast rate, it's not even day one of the platform.

However, I want to use the web client, but nothing shows up:
![image](https://github.com/junhoyeo/threads-api/assets/15577163/293bed55-cd28-439b-9afb-f137453dcd01)
And when i try accessing any username: 
![image](https://github.com/junhoyeo/threads-api/assets/15577163/fbb90ad8-b918-46b1-bdd9-27a0e9232257)

I'm running the script with npm run dev, am i doing something wrong?
![image](https://github.com/junhoyeo/threads-api/assets/15577163/89e01cc1-b821-4f52-8c86-2bde3ec13531)

**Comment by junhoyeo** [comment]
Hi there, @torrober!
I hadn't added anything to the root page(`/`) yet, but the username page should work!
Did you run `yarn workspace threads-api build` before running `yarn workspace threads-web-ui dev`?

**Comment by Mineru98** [comment]
> Hi there, @torrober! I hadn't added anything to the root page(`/`) yet, but the username page should work! Did you run `yarn workspace threads-api build` before running `yarn workspace threads-web-ui dev`?

I think we need more description in README.md

**Comment by torrober** [comment]
@Mineru98  I agree.

**Comment by torrober** [comment]
Still couldn't run the web client, i'm having errors with the threads library or the next framework.

How am I supposed to run the client from scratch? i have tried anything but nothing.

**Comment by junhoyeo** [comment]
@torrober I'll check on this issue.

**Comment by junhoyeo** [comment]
@torrober yo i think this was resolved a while ago. Can you try running the web client again with the latest commit?

```bash
yarn # Install dependencies

yarn workspace threads-api build # Build `threads-api`
yarn workspace threads-web-ui dev # Run dev server

# Visit http://localhost:3000/_junhoyeo to check 
```

I'll add proper documentation & improve the client before closing this issue!

**Comment by torrober** [comment]
![image](https://github.com/junhoyeo/threads-api/assets/15577163/f18ce64f-ffb8-4a1f-ac67-5dc1f151376c)
I Got the website working, but there's a problem related with requesting threads.

**Comment by torrober** [comment]
![image](https://github.com/junhoyeo/threads-api/assets/15577163/5ddb8bae-516f-45ba-af95-e2028f8126e4)
Page still showing 404 error

**Comment by torrober** [comment]
![image](https://github.com/junhoyeo/threads-api/assets/15577163/a8db34c5-1559-4945-8032-19d45ce65e88)
Too many redirs..

**Comment by junhoyeo** [comment]
Strange, will check and update.

**Comment by torrober** [comment]
Just updated to the newest release, and everything works fine! 
![image](https://github.com/junhoyeo/threads-api/assets/15577163/a38abe40-52cd-4f86-99e1-2893bb4a54e5)
However, i had to run with git bash terminal, idk if its something related to powershell or non unix/linux systems, but please take consideration of that.

The redir error was fixed thanks to the proxy.

**Comment by threaderzero** [comment]
I cannot run it either, but I have another error code: `EHOSTUNREACH` :S

```
    _currentUrl: 'https://www.instagram.com/_junhoyeo',
    [Symbol(kCapture)]: false
  },
  cause: AggregateError
      at internalConnectMultiple (node:net:1103:18)
      at internalConnectMultiple (node:net:1161:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1638:3)
      at listOnTimeout (node:internal/timers:575:11)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'EHOSTUNREACH',
    [errors]: [ [Error] ]
  }
```

Running on macOS, I visit `http://localhost:3000/_junhoyeo` after I run `yarn workspace threads-web-ui dev` with bash and zsh, same result

**Comment by threaderzero** [comment]
Seeing this on your page. zuck's page works fine tho 

<img width="1043" alt="image" src="https://github.com/junhoyeo/threads-api/assets/139019903/c5e21d41-9db9-4463-a92e-7d28b463ad0e">

**Comment by Mineru98** [comment]
@threaderzero Check [this commit](https://github.com/junhoyeo/threads-api/pull/52/commits/0e59189271447e69bab57e558b4a0bc4d16f6942)

**Comment by iamdeepak92** [comment]
This is the first Threads scraper code. This requires no login . I think this will help someone.

https://github.com/iamdeepak92/threads-scraper

**Comment by junhoyeo** [comment]
Believe this is fixed! 🥳
