### ISSUE TITLE
Unhandled error AxiosError: Request failed with status code 429

### ISSUE THREAD

**Issue by dLiubchenko** [junhoyeo/threads-api#217]
I am encountering an error 429 (too many requests) while utilizing the Threads API on Firebase Functions. Below is the code for my function that is being called from the Swift application. I think it's happening on background login. It's working fine locally, but not on the Firebase Functions side.

<img width="803" alt="image" src="https://github.com/junhoyeo/threads-api/assets/93602147/1634d6a3-f784-45bc-9c31-0305cdb718b3">

**Comment by dLiubchenko** [comment]
I'm trying to use proxy provider for that - and nothing... I think proxy provider must to be implemented in the API side when the app trying to request endpoint of login

**Comment by junhoyeo** [comment]
@dLiubchenko Hi there! We believe this issue have been fixed now. Can you try again with the latest version?
👉  https://github.com/junhoyeo/threads-api/releases/tag/v1.5.3

**Comment by dLiubchenko** [comment]
@junhoyeo Im sorry, but Firebase is still experiencing a 429 error ☹️
